spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: maria
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # pode ser 'create' para criar do zero
    show-sql: true

