
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/transactiondb
    username: postgres
    password: maria
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


