version: '3.8'

services:
  postgres-transaction:
    image: postgres:14
    container_name: postgres-transaction
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql/data

volumes:
  transaction_db_data:
