version: '3.8'

services:
  db:
    image: postgres:14           # imagem oficial do PostgreSQL
    container_name: usersdb
    restart: always
    environment:
      POSTGRES_USER: postgres       # usuário do banco
      POSTGRES_PASSWORD: maria  # senha do banco
      POSTGRES_DB: usersdb    # nome do banco
    ports:
      - "8081:5432"              # porta 8081 no host -> 5432 no container
    volumes:
      - db_data:/var/lib/postgresql/data  # mantém os dados

volumes:
  db_data:
